### ISSUE TITLE
It does not work in Visual Studio 2015.

### ISSUE THREAD

**Issue by steamb23** [jz5/Pronama-chanIDE2013#1]
Since the 1.2 update, the Pronama chan is not drawn.
I can not work without her. Please solve it as soon as possible.
![2016-12-01 02_42_08-the abyss - microsoft visual studio](https://cloud.githubusercontent.com/assets/6805899/20764131/2996da0a-b770-11e6-8039-b72f643f4378.png)

**Comment by jz5** [comment]
Thank you for your report.
I check for this issue.

**Comment by jz5** [comment]
Could you please check for ver 1.21?

**Comment by steamb23** [comment]
ver 1.21 works well with Visual Studio 2015. Thanks for fixing! :)
